Endpoint recomendaciones
CarlosSoPe6/iteso-covid pull request #12
Opened 2020-10-23 17:28 UTC by pallaro98

2020-10-23 18:39 UTC, Isaac2357 requested changes
Hay que hacer el refactor para utilizar el contexto de ejecución. Puedes basarte en mis endpoits para hacerlo. Básicamente es pasar la conexión al modelo desdee el contexto de ejecución

2020-10-24 17:06 UTC, CarlosSoPe6 commented
Resolver conflictos antes del próximo commit. Hacer merge con origin/master

2020-10-24 17:07 UTC, CarlosSoPe6 submitted a review, later dismissed
Arreglar lo de los conflictos y el contexto de ejecución

2020-10-25 23:45 UTC, Isaac2357 approved these changes

2020-10-25 23:46 UTC, merged

2020-10-26 01:12 UTC, pallaro98 reviewed
Muy buen trabajo Isaac!